bridge:
    enabled: true
    max-length: 32
    allowed-materials: [4, 5, 22, 24, 35, 41, 42, 44, 45, 48, 57, 80]
gate:
    enabled: true
    max-length: 32
    max-width: 3
door:
    enabled: true
    max-height: 32
    allowed-materials: [4, 5, 22, 24, 35, 41, 42, 45, 47, 48, 49, 57, 80]
hidden-switch:
    enabled: true
lift:
    enabled: true
    max-search-height: 32
ammeter:
    enabled: true
cauldron:
    enabled: true
pen:
    enabled: true
    material: 263

use-permissions: true
use-worldguard: false
use-zones: false